# Generated by Django 4.1.1 on 2022-10-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichas',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
