# Generated by Django 4.1.1 on 2022-09-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='historiaPersonagem',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
