# Generated by Django 4.1.1 on 2022-09-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_ficha_historiapersonagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='LVL',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=2),
        ),
    ]
