# Generated by Django 4.1.1 on 2022-10-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_fichas_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='AGL',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='CAR',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='CON',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='CTF',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='DES',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='FOR',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='LUT',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='LVL',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='PER',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='SAB',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='VIT',
            field=models.IntegerField(default=0),
        ),
    ]
