# Generated by Django 4.1.1 on 2022-10-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_alter_fichas_agl_alter_fichas_car_alter_fichas_con_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='AGL',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='CAR',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='CON',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='CTF',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='DES',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='LVL',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='PER',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='SAB',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='user',
            field=models.IntegerField(),
        ),
    ]
