# Generated by Django 4.1.1 on 2022-10-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_alter_fichas_agl_alter_fichas_car_alter_fichas_con_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='nomePersonagem',
            field=models.CharField(default='Pedro', max_length=45),
        ),
    ]
