# Generated by Django 4.1.1 on 2022-09-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_alter_ficha_lvl'),
    ]

    operations = [
        migrations.CreateModel(
            name='fichas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePersonagem', models.CharField(max_length=45)),
                ('historiaPersonagem', models.TextField(blank=True, max_length=1000)),
                ('SAB', models.CharField(max_length=2)),
                ('AGL', models.CharField(max_length=2)),
                ('CON', models.CharField(max_length=2)),
                ('DES', models.CharField(max_length=2)),
                ('CTF', models.CharField(max_length=2)),
                ('PER', models.CharField(max_length=2)),
                ('CAR', models.CharField(max_length=2)),
                ('VIT', models.CharField(max_length=2)),
                ('FOR', models.CharField(max_length=2)),
                ('LUT', models.CharField(max_length=2)),
                ('LVL', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17')], default='1', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='ficha',
        ),
    ]
