# Generated by Django 4.1.1 on 2022-10-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0005_alter_fichas_nomepersonagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='nomePersonagem',
            field=models.CharField(blank=True, default='Pedro', max_length=45),
        ),
    ]
