# Generated by Django 4.1.1 on 2022-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0008_alter_fichas_nomepersonagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='nomePersonagem',
            field=models.CharField(blank=True, default='0', max_length=45, null=True),
        ),
    ]
