# Generated by Django 4.1.1 on 2022-10-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0010_alter_fichas_nomepersonagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichas',
            old_name='AGL',
            new_name='Agilidade',
        ),
        migrations.RenameField(
            model_name='fichas',
            old_name='CAR',
            new_name='Carisma',
        ),
        migrations.RenameField(
            model_name='fichas',
            old_name='CON',
            new_name='Conhecimento',
        ),
        migrations.RenameField(
            model_name='fichas',
            old_name='CTF',
            new_name='ConstFisica',
        ),
        migrations.RenameField(
            model_name='fichas',
            old_name='DES',
            new_name='Destreza',
        ),
        migrations.RenameField(
            model_name='fichas',
            old_name='FOR',
            new_name='Força',
        ),
        migrations.RenameField(
            model_name='fichas',
            old_name='LVL',
            new_name='Level',
        ),
        migrations.RenameField(
            model_name='fichas',
            old_name='LUT',
            new_name='Luta',
        ),
        migrations.RenameField(
            model_name='fichas',
            old_name='PER',
            new_name='Percepção',
        ),
        migrations.RenameField(
            model_name='fichas',
            old_name='SAB',
            new_name='Sabedoria',
        ),
        migrations.RenameField(
            model_name='fichas',
            old_name='VIT',
            new_name='Vitalidade',
        ),
        migrations.RemoveField(
            model_name='fichas',
            name='user',
        ),
        migrations.AlterField(
            model_name='fichas',
            name='nomePersonagem',
            field=models.CharField(max_length=45),
        ),
    ]
