# Generated by Django 4.1.1 on 2022-10-20 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha', '0011_rename_agl_fichas_agilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichas',
            name='preencher_ficha',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
