# Generated by Django 4.1 on 2022-10-23 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aventura', '0002_rename_aventura_aventuras'),
        ('ficha', '0012_fichas_preencher_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichas',
            name='id_aventura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aventura.aventuras'),
        ),
    ]
