# Generated by Django 4.1 on 2022-10-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aventura', '0003_aventuras_jogar_aventura'),
        ('ficha', '0013_fichas_id_aventura'),
    ]

    operations = [
        migrations.CreateModel(
            name='possuir_equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='fichas',
            name='id_aventura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aventura.aventuras'),
        ),
        migrations.CreateModel(
            name='pericias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pericia', models.CharField(max_length=30, unique=True)),
                ('descrição_pericia', models.CharField(max_length=100)),
                ('conter_pericia', models.ManyToManyField(to='ficha.fichas')),
            ],
        ),
        migrations.CreateModel(
            name='equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equi', models.CharField(max_length=20, unique=True)),
                ('dano', models.IntegerField(blank=True, null=True)),
                ('defesa', models.IntegerField(blank=True, null=True)),
                ('descrição', models.CharField(max_length=100)),
                ('possuir_equipamento', models.ManyToManyField(to='ficha.fichas')),
            ],
        ),
    ]
