# Generated by Django 4.1 on 2022-10-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0014_possuir_equipamento_alter_fichas_id_aventura_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='possuir_equipamento',
        ),
        migrations.RemoveField(
            model_name='equipamentos',
            name='possuir_equipamento',
        ),
        migrations.AddField(
            model_name='equipamentos',
            name='possuir_equipamento',
            field=models.IntegerField(default=0),
        ),
    ]
