# Generated by Django 4.1 on 2022-10-23 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0015_delete_possuir_equipamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamentos',
            name='possuir_equipamento',
        ),
        migrations.CreateModel(
            name='possuir_equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.equipamentos')),
                ('id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.fichas')),
            ],
        ),
    ]
