# Generated by Django 4.1 on 2022-11-11 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha', '0017_possuir_equipamento_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='preencher_ficha',
            field=models.ManyToManyField(related_name='preencher_ficha', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pericias',
            name='conter_pericia',
            field=models.ManyToManyField(related_name='conter_pericia', to='ficha.fichas'),
        ),
    ]
