# Generated by Django 4.1 on 2022-11-21 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aventura', '0003_aventuras_jogar_aventura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha', '0018_alter_fichas_preencher_ficha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='historiaPersonagem',
            field=models.TextField(max_length=1000, verbose_name='Historia do Personagem'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='id_aventura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aventura.aventuras', verbose_name='Aventura'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='nomePersonagem',
            field=models.CharField(max_length=45, verbose_name='Nome do Personagem'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='preencher_ficha',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
