# Generated by Django 4.1.1 on 2022-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeJogador', models.CharField(max_length=50)),
                ('emailJogador', models.CharField(max_length=100, unique=True)),
                ('senhaJogador', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='mestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMestre', models.CharField(max_length=50)),
                ('emailMestre', models.CharField(max_length=100, unique=True)),
                ('senhaMestre', models.CharField(max_length=255)),
            ],
        ),
    ]
