# Generated by Django 4.1 on 2022-10-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aventura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAventura', models.CharField(max_length=100, unique=True)),
                ('guia_de_ambiente', models.CharField(blank=True, max_length=100)),
                ('historia_aventura', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
