# Generated by Django 4.1 on 2022-10-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aventura', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aventura',
            new_name='aventuras',
        ),
    ]
