# Generated by Django 4.1 on 2022-10-23 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aventura', '0002_rename_aventura_aventuras'),
    ]

    operations = [
        migrations.AddField(
            model_name='aventuras',
            name='jogar_aventura',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
