# Generated by Django 4.0.6 on 2022-07-29 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ('-publicado',)},
        ),
        migrations.RemoveField(
            model_name='questions',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='questions',
            name='publicado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
